# Those are params for usage with docker
parameters:
    database_driver: pdo_mysql
    database_host: db
    database_port: 3306
    database_name: munchkindb
    database_user: root
    database_password: password
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: ThisTokenIsNotSoSecretChangeIt
    long_cache: 86400
    short_cache: 600
    assets_version: 1
    locale_names: en
    supported_locales:
        - en
    oauth_test_client_id: null
    oauth_test_client_secret: null
    oauth_test_redirect_uri: null
    images_path: null
