AppBundle\Entity\Card:
    type: entity
    table: card
    repositoryClass: AppBundle\Repository\CardRepository
    gedmo:
        translation:
            locale: locale
    indexes:
        title_index:
            columns: [ title ]
        gold_index:
            columns: [ gold ]
        rank_index:
            columns: [ rank ]
        code_index:
            columns: [ code ]
    manyToOne:
        pack:
            targetEntity: Pack
            inversedBy: cards
            joinColumn:
                name: pack_id
                referencedColumnName: id
        side: 
            targetEntity: Side
            inversedBy: cards
            joinColumn:
                name: side_id
                referencedColumnName: id
        type:
            targetEntity: Type
            inversedBy: cards
            joinColumn:
                name: type_id
                referencedColumnName: id
        faction:
            targetEntity: Faction
            inversedBy: cards
            nullable: true
            joinColumn:
                name: faction_id
                referencedColumnName: id
    oneToMany:
        decklists:
            targetEntity: Decklist
            orderBy: {'dateCreation':'DESC'}
            mappedBy: identity
        reviews:
            targetEntity: Review
            orderBy: {'dateCreation':'DESC'}
            mappedBy: card
        rulings:
            targetEntity: Ruling
            orderBy: {'dateCreation':'DESC'}
            mappedBy: card
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        position:
            type: integer
        dateUpdate:
            type: datetime
            nullable: false
            column: date_update
            gedmo:
                timestampable:
                    on:  update
        dateCreation:
            type: datetime
            nullable: false
            column: date_creation
            gedmo:
                timestampable:
                    on: create
        code:
            type: string
            unique: true
        title:
            type: string
            length: 1024
            gedmo:
                - translatable
        keywords:
            type: string
            length: 255
            nullable: true
            gedmo:
                - translatable
        text:
            type: string
            length: 1024
            nullable: true
            gedmo:
                - translatable
        gold:
            type: smallint
            nullable: true
        rank:
            type: smallint
            nullable: true
        minimumDeckSize:
            type: smallint
            column: minimum_deck_size
            nullable: true
        life:
            type: smallint
            nullable: true
        quantity:
            type: smallint
            nullable: true
        power:
             type: smallint
             nullable: true
        defense:
              type: smallint
              nullable: true
        uniqueness:
            type: boolean
            nullable: true
        deckLimit:
            type: smallint
            column: deck_limit
            nullable: true
        imageUrl:
            type: string
            column: image_url
            nullable: true
        illustrator:
                type: string
                nullable: true
        colorist:
                type: string
                nullable: true
        rarity:
                type: string
                length: 256
    lifecycleCallbacks: {  }
